name: Build and Push Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # keyless 서명용
      packages: write # GHCR push 권한

    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/application

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase owner/env
        shell: bash
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/application" >> $GITHUB_ENV
          echo "TEAM=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        id: push
        with:
          context: ./step10-cicd
          file: ./step10-cicd/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.run_number }}
            ${{ env.IMAGE }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TEAM=${{ env.TEAM }}
            COLOR=${{ secrets.TEAM_COLOR }}

      # Trivy로 빌드된 이미지 scan -> 취약점 발견 시 실패 (보안 게이트 역할)
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "${{ env.IMAGE }}@${{ steps.push.outputs.digest }}"
          format: "table"
          severity: "CRITICAL,HIGH,MEDIUM"
          exit-code: 1

      # CycloneDX 포맷으로 SBOM 생성
      - name: Generate SBOM with Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "${{ env.IMAGE }}@${{ steps.push.outputs.digest }}"
          scan-type: "image"
          format: "cyclonedx"
          output: "sbom.json"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      # 이미지 서명 (keyless)
      - name: Sign Container Image
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
        run: |
          cosign sign --yes \
            ${{ env.IMAGE }}:sha-${{ github.sha }}

      # sbom.json 파일을 이미지에 증명용으로 첨부
      # 이미지 내부에 GHCR 메타데이터로 구성요소들이 남아있음
      - name: Attest SBOM
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
        run: |
          cosign attest --yes \
            --predicate sbom.json \
            --type cyclonedx \
            ${{ env.IMAGE }}:sha-${{ github.sha }}

      - name: Verify image base
        run: |
          echo "Checking image layers and base..."
          docker pull ${{ env.IMAGE }}:sha-${{ github.sha }}
          docker history ${{ env.IMAGE }}:sha-${{ github.sha }} --no-trunc
          echo "Image verification completed successfully"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
            IMAGE="ghcr.io/${OWNER_LC}/application"
            docker login ghcr.io -u '${{ github.actor }}' -p '${{ secrets.GHCR_READ_TOKEN }}'
            docker pull "${IMAGE}:sha-${{ github.sha }}"
            docker rm -f app || true
            docker run -d --name app -p 8080:8080 "${IMAGE}:sha-${{ github.sha }}"
